version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/CognitiveServices.Explorer"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: Microsoft.AspNetCore.Components.WebAssembly.DevServer
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Snapshooter.Xunit
    versions:
    - 0.5.8
    - 0.6.1
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: Moq
    versions:
    - 4.16.0
