name: Build and deploy

on:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    if: github.event.action == 'run_tests'
    name: Run your tests
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: dotnet test ./src/CognitiveServices.Explorer/CognitiveServices.Explorer.sln --configuration Release

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Dump GitHub context
      run: echo Deployment for ${{ github.ref }}
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.300-preview-015048
        
    # Make sure the icons are configured correctly for DEV
    - name: Copy file
      if: github.ref == 'refs/heads/dev'
      uses: canastro/copy-action@0.0.2
      with:
        # Source file
        source: ./wwwroot/android-chrome-192x192-dev.png
        # Target file
        target: ./wwwroot/android-chrome-192x192.png

    # Replace values in appsettings.json (prod only)
    - uses: microsoft/variable-substitution@v1 
      with:
        files: './src/CognitiveServices.Explorer/CognitiveServices.Explorer.Web/appsettings.json'
      env:
        IsDev: false
        Environment: "Prod"
        Title: Cognitive Studio
    
    - name: Test
      run: dotnet test ./src/CognitiveServices.Explorer/CognitiveServices.Explorer.sln --configuration Release
      
    - name: Publish
      run: dotnet publish ./src/CognitiveServices.Explorer/ -c Release -o ./dist/
    
    - name: Azure Blob Storage Upload (production)
      if: github.ref == 'refs/heads/master'
      uses: bacongobbler/azure-blob-storage-upload@v1.0.0
      with:
        # The name of the directory you want to upload
        source_dir: ./dist/wwwroot/
        # The name of the storage account container these assets will be uploaded to
        container_name: $web
        # The connection string for the storage account
        connection_string: ${{secrets.AzureBlobStorageConnectionString}}
        # extra arguments that can be passed to `az storage blob upload-batch`. Useful for passing flags like `--pattern` or `--destination-path`
        #extra_args: # optional
          
    - name: Azure Blob Storage Upload (dev)
      if: github.ref == 'refs/heads/dev'
      uses: bacongobbler/azure-blob-storage-upload@v1.0.0
      with:
        # The name of the directory you want to upload
        source_dir: ./dist/wwwroot/
        # The name of the storage account container these assets will be uploaded to
        container_name: $web
        # The connection string for the storage account
        connection_string: ${{secrets. AzureDevBlobStorageConnectionString}}
        # extra arguments that can be passed to `az storage blob upload-batch`. Useful for passing flags like `--pattern` or `--destination-path`
        #extra_args: # optional
