name: .NET Core

on: [push]

jobs:
  test:
    if: github.event.action == 'run_tests'
    name: Run your tests
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: dotnet test ./src/CognitiveServices.Explorer/CognitiveServices.Explorer.sln --configuration Release

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.101
    
    - name: Test
      run: dotnet test ./src/CognitiveServices.Explorer/CognitiveServices.Explorer.sln --configuration Release
      
    - name: Publish
      run: dotnet publish ./src/CognitiveServices.Explorer/ -c Release -o ./dist/
    
    - name: Azure Blob Storage Upload
      uses: bacongobbler/azure-blob-storage-upload@v1.0.0
      with:
        # The name of the directory you want to upload
        source_dir: ./dist/CognitiveServices.Explorer.Web/dist/
        # The name of the storage account container these assets will be uploaded to
        container_name: $web
        # The connection string for the storage account
        connection_string: ${{secrets.AzureBlobStorageConnectionString}}
        # extra arguments that can be passed to `az storage blob upload-batch`. Useful for passing flags like `--pattern` or `--destination-path`
        #extra_args: # optional
